server:
  # Port sur lequel la gateway écoutera. 
  # Mis à 8080 pour correspondre à votre config front et docker-compose.
  port: 8080

spring:
  application:
    # Nom de l'application, il apparaîtra dans Eureka.
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # Permet à la gateway de créer des routes automatiquement à partir d'Eureka.
          enabled: true
          # Met les noms des services en minuscules.
          lower-case-service-id: true
  
  # =============================================
  # == CONFIGURATION DE SÉCURITÉ À AJOUTER ==
  # =============================================
  security:
    oauth2:
      resourceserver:
        jwt:
          # C'est l'URL de votre realm Keycloak.
          # 'keycloak' est le nom du service dans votre réseau Docker.
          # 'eventy-realm' est le nom de votre realm.
          issuer-uri: http://keycloak:8090/realms/eventy-realm

# Configuration du client Eureka pour trouver les autres services.
eureka:
  client:
    service-url:
      # L'URL de votre serveur Eureka. 
      # Remplacé 'localhost' par 'eureka' pour être compatible Docker.
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true

# Active les logs de la gateway pour le débogage.
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG # Ajouté pour débugger la sécurité